### PR TITLE
f2 conflicts with file tree:rename

### PR DESCRIPTION
**Pull request by valtido**
The f2 should be for renaming conventions so changed f2 to alt+f2

### CODE REVIEW

**Comment by thomasjo** [comment]
The keybind in question is scoped to `atom-text-editor`, so it will not be triggered in the tree-view, so there is no conflict.

**Comment by valtido** [comment]
for me this is not working on win 7,

maybe it's because it says `tree-view: move`, instead of `treeview: rename`

so I have disabled the bookmark and wrote the shortcut on my keymap for it to work.

**Comment by izuzak** [comment]
> maybe it's because it says tree-view: move, instead of treeview: rename

@valtido Strange, [as far as I can tell](https://github.com/atom/tree-view/blob/34223477d5c4dd0614b0d2355c439deb16cbcf99/keymaps/tree-view.cson#L73) -- the keystroke is bound to `tree-view: move`. Can you share a link which suggests otherwise and a screenshot of the [keybinding resolved](https://atom.io/docs/latest/hacking-atom-debugging#check-the-keybindings) which demonstrates this problem?

**Comment by kevinsawicki** [comment]
Closing this out for now, we can reopen after you provide the details in @izuzak's previous comment.

**Pull request closed without merging**
