### PR TITLE
Center on selection on jump to bookmark

### LINKED ISSUE #32: Center bookmarks vertically on jump
When cycling through bookmarks, especially in really long files, bookmark jumping feels jarring.

Sometimes a bookmark will be in the top section of the view window, and sometimes towards the bottom.  For example, when the bookmark cycling wraps around to the first bookmark in the file, the bookmark will be on the top of the view. When you cycle to the next bookmark towards the bottom of the file, the bookmark will be on the bottom of the view. This also will occur if using 'next bookmark' followed by 'previous bookmark' when the bookmarks are not within the same view.

It would be a nice option to be able to enable a 'center bookmark on jump' option, which will scroll the view so that the bookmark is in the center (vertical) of the window if possible. This would provide some consistency to bookmark positions when cycling through long files with many bookmarks. If the bookmarks are already within the same view prior to the jump, the view positioning should not change (which is how it is currently).

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #32

### CODE REVIEW

**Comment by Tyriar** [comment]
I tried writing a test for this as below but `editor` doesn't seem to have either `onDidRequestAutoscroll` or `onDidChangeScrollPosition` available. Not sure why.

```coffeescript
it "centers bookmarks in the text editor", ->
  scrollSpy = jasmine.createSpy("::onDidRequestAutoscroll")

  editor.onDidRequestAutoscroll(scrollSpy)
  editor.setCursorBufferPosition([0, 0])

  atom.commands.dispatch editorElement, 'bookmarks:jump-to-next-bookmark'
  expect(editor.getLastCursor().getBufferPosition()).toEqual [2, 0]

  atom.commands.dispatch editorElement, 'bookmarks:jump-to-next-bookmark'
  expect(editor.getLastCursor().getBufferPosition()).toEqual [10, 0]

  atom.commands.dispatch editorElement, 'bookmarks:jump-to-next-bookmark'
  expect(editor.getLastCursor().getBufferPosition()).toEqual [2, 0]

  expect(scrollSpy).toHaveBeenCalledWith(screenRange: [[2, 0], [2, 0]], options: {center: true})
  expect(scrollSpy).toHaveBeenCalledWith(screenRange: [[10, 0], [10, 0]], options: {center: true})
  expect(scrollSpy).toHaveBeenCalledWith(screenRange: [[2, 0], [2, 0]], options: {center: true})
```

**Comment by Alhadis** [comment]
Somebody merge this, for the love of all that is good.

<3

**Comment by Tyriar** [comment]
Ping - this is one of the more simple PRs I have out. Super trivial but really useful to bookmarks users.

**Comment by lee-dohm** [comment]
Thanks for the ping @Tyriar. We've got some new people on the team, so hopefully PR responsiveness will pick up :grinning:

**Comment by lee-dohm** [comment]
Thanks again for contributing :grinning:

**Pull request merged**
